package com.marcosmoreiradev.uensdesktop.ui.assets;

public enum UiAssetId {
    BRAND_LOGO,
    BRAND_ICON,
    INFORMATION_ICON,
    LOGOUT_TICK,
    LOGIN_CONTEXT,
    DASHBOARD_CONTEXT,
    ESTUDIANTES_CONTEXT,
    REPRESENTANTES_CONTEXT,
    DOCENTES_CONTEXT,
    SECCIONES_CONTEXT,
    ASIGNATURAS_CONTEXT,
    CLASES_CONTEXT,
    CALIFICACIONES_CONTEXT,
    REPORTES_CONTEXT,
    AUDITORIA_CONTEXT
}
